### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by PlebeiusGaragicus** [EddWills95/UmbrUI#27]
How's this project going?

Any way this can be updated to work with Umbrel's new community app stores?

**Comment by AaronDewes** [comment]
Right now, it's unmaintained. I'll check if it can be turned into a community app, but it'll definitely be integrated into [Citadel](https://runcitadel.space) in the future.

**Comment by EddWills95** [comment]
We'd love to. The biggest issue is enabling the framebuffer and SPI interface at the OS level which is not something umbrel has. The docker-compose can then expose that part of the filesystem `/dev/SPI0` (or something like that from memory) to the docker container. Aaron and I had a lot of problems trying to get that working nicely with umbrel 
But this could certainly be a good jumping off point if things change for Umbrel

**Comment by PlebeiusGaragicus** [comment]
I had completely forgotten about Citadel!  I would LOVE to contribute to Citadel once it's up and running!

I'm a complete beginner at this but am already unsure of how Umbrel is going to work out.  They have a lot of work to do - agreed.
